export const qk = {
  universes: () => ['universes'] as const,
  universe: (id: number) => ['universes', id] as const,
  metrics: (id: number) => ['universes', id, 'metrics'] as const,
  snapshot: (id: number, tick: number) => ['universes', id, 'snapshot', tick] as const,
  chronicles: (id: number) => ['universes', id, 'chronicles'] as const,
  chronicle: (chronicleId: number) => ['chronicles', chronicleId] as const,
  feed: (id: number, types: string[] = []) =>
    ['universes', id, 'feed', [...types].sort().join(',')] as const,
  actors: (id: number) => ['universes', id, 'actors'] as const,
  actorPsyche: (actorId: number) => ['actors', actorId, 'psyche'] as const,
  supremeEntities: (id: number) => ['universes', id, 'supreme-entities'] as const,
  civilization: (id: number) => ['universes', id, 'civilization'] as const,
  worldState: (id: number) => ['universes', id, 'world'] as const,
  topology: (id: number) => ['universes', id, 'topology'] as const,
  causalLinks: (id: number, fromTick?: number, toTick?: number) =>
    ['universes', id, 'causal-links', fromTick ?? null, toTick ?? null] as const,
  realityState: (id: number) => ['universes', id, 'reality-state'] as const,
  wavefunction: (id: number) => ['universes', id, 'wavefunction'] as const,
  informationalMass: (id: number) => ['universes', id, 'informational-mass'] as const,
  consciousness: (id: number) => ['universes', id, 'consciousness'] as const,
  ascensionFilters: (id: number) => ['universes', id, 'ascension-filters'] as const,
  stateDelta: (id: number) => ['universes', id, 'state-delta'] as const,
  bloom: () => ['multiverse', 'bloom'] as const,
  resonance: () => ['multiverse', 'resonance'] as const,
  forkTree: () => ['multiverse', 'fork-tree'] as const,
  serviceStatus: () => ['ops', 'service-status'] as const,
  simulationSettings: () => ['ops', 'simulation-settings'] as const,
  aiSettings: () => ['ops', 'ai-settings'] as const,
  providerModels: () => ['ops', 'provider-models'] as const,
  keyPool: () => ['ops', 'key-pool'] as const,
  loomAgents: () => ['ops', 'loom-agents'] as const,
  aiDrivers: () => ['ops', 'ai-drivers'] as const,
  aiLogs: (filters: string) => ['ops', 'ai-logs', filters] as const,
  aiStats: () => ['ops', 'ai-stats'] as const,
  loomStatus: () => ['loom', 'status'] as const,
  loomTask: (taskId: string) => ['loom', 'task', taskId] as const,
  snapshots: (id: number) => ['universes', id, 'snapshots'] as const,
  forks: (id: number) => ['universes', id, 'forks'] as const,
} as const;
