export const qk = {
  universes: () => ['universes'] as const,
  universe: (id: number) => ['universes', id] as const,
  metrics: (id: number) => ['universes', id, 'metrics'] as const,
  snapshot: (id: number, tick: number) => ['universes', id, 'snapshot', tick] as const,
  chronicles: (id: number) => ['universes', id, 'chronicles'] as const,
  chronicle: (chronicleId: number) => ['chronicles', chronicleId] as const,
  feed: (id: number, types: string[] = []) =>
    ['universes', id, 'feed', [...types].sort().join(',')] as const,
  actors: (id: number) => ['universes', id, 'actors'] as const,
  actorPsyche: (actorId: number) => ['actors', actorId, 'psyche'] as const,
  supremeEntities: (id: number) => ['universes', id, 'supreme-entities'] as const,
  civilization: (id: number) => ['universes', id, 'civilization'] as const,
  worldState: (id: number) => ['universes', id, 'world'] as const,
  topology: (id: number) => ['universes', id, 'topology'] as const,
  causalLinks: (id: number, fromTick?: number, toTick?: number) =>
    ['universes', id, 'causal-links', fromTick ?? null, toTick ?? null] as const,
  realityState: (id: number) => ['universes', id, 'reality-state'] as const,
  wavefunction: (id: number) => ['universes', id, 'wavefunction'] as const,
  informationalMass: (id: number) => ['universes', id, 'informational-mass'] as const,
  consciousness: (id: number) => ['universes', id, 'consciousness'] as const,
  ascensionFilters: (id: number) => ['universes', id, 'ascension-filters'] as const,
  stateDelta: (id: number) => ['universes', id, 'state-delta'] as const,
  bloom: () => ['multiverse', 'bloom'] as const,
  resonance: () => ['multiverse', 'resonance'] as const,
  forkTree: () => ['multiverse', 'fork-tree'] as const,
} as const;
