"""Pipeline Manifest — single source of truth for the Narrative Loom graph."""

PIPELINE_MANIFEST = {
    "version": "2.0",
    "total_nodes": 18,
    "nodes": [
        {"id": "Event_Normalizer", "label": "Event Normalizer", "short_label": "Normalizer", "phase": "engine", "role": "Normalize raw events", "description": "Parses and normalizes raw simulation events into structured narrative inputs."},
        {"id": "Universe_Bridge", "label": "Universe Bridge", "short_label": "Bridge", "phase": "engine", "role": "Bridge universe state", "description": "Connects current universe state vector to the narrative pipeline."},
        {"id": "Entropy_Engine", "label": "Entropy Engine", "short_label": "Entropy", "phase": "engine", "role": "Measure chaos", "description": "Quantifies narrative chaos and unpredictability in the current tick window."},
        {"id": "Style_Analyzer", "label": "Style Analyzer", "short_label": "Style", "phase": "engine", "role": "Detect genre", "description": "Detects the dominant genre and stylistic register from world state."},
        {"id": "Attractor_Engine", "label": "Attractor Engine", "short_label": "Attractor", "phase": "engine", "role": "Find patterns", "description": "Identifies recurring narrative attractors and civilization patterns."},
        {"id": "Dramatic_Arc", "label": "Dramatic Arc", "short_label": "Arc", "phase": "engine", "role": "Build tension curve", "description": "Constructs the overall dramatic tension curve across the tick range."},
        {"id": "Phase_Engine", "label": "Phase Engine", "short_label": "Phase", "phase": "engine", "role": "Detect narrative phase", "description": "Determines which narrative phase (exposition, rising, climax, resolution) applies."},
        {"id": "Singularity_Engine", "label": "Singularity Engine", "short_label": "Singularity", "phase": "engine", "role": "Flag irreversible events", "description": "Flags pivotal, irreversible moments that should dominate the chronicle."},
        {"id": "Chief_Editor", "label": "Chief Editor", "short_label": "Editor", "phase": "agent", "role": "Set editorial angle", "description": "Defines the central voice, theme, and narrative mandate for the creative phase."},
        {"id": "The_Historian", "label": "Historian", "short_label": "Historian", "phase": "agent", "role": "Write historical outline", "description": "Turns normalized events into a structured backbone with causal ordering."},
        {"id": "The_Mythologist", "label": "Mythologist", "short_label": "Mythologist", "phase": "agent", "role": "Overlay mythic meaning", "description": "Adds archetypes, symbols, and legendary resonance to the outline."},
        {"id": "The_Psychologist", "label": "Psychologist", "short_label": "Psychologist", "phase": "agent", "role": "Profile motivations", "description": "Builds psychological context for key actors and pressures on the narrative."},
        {"id": "The_Director", "label": "Director", "short_label": "Director", "phase": "agent", "role": "Storyboard scenes", "description": "Translates the outline into scenes, pacing, and visual narrative beats."},
        {"id": "The_Wordsmith", "label": "Wordsmith", "short_label": "Wordsmith", "phase": "agent", "role": "Write final prose", "description": "Produces the actual chronicle prose from the storyboard and editorial directives."},
        {"id": "The_Critic", "label": "Critic", "short_label": "Critic", "phase": "agent", "role": "Evaluate and revise", "description": "Runs quality control and may trigger revision loops back into Wordsmith."},
        {"id": "VFX_Director", "label": "VFX Director", "short_label": "VFX", "phase": "agent", "role": "Generate visual mood cues", "description": "Prepares visual effects hints and atmosphere metadata for presentation layers."},
        {"id": "The_Archivist", "label": "Archivist", "short_label": "Archivist", "phase": "agent", "role": "Persist approved output", "description": "Archives the approved chronicle and prepares metadata for downstream consumers."},
        {"id": "News_Anchor", "label": "News Anchor", "short_label": "Anchor", "phase": "agent", "role": "Generate headlines", "description": "Produces concise in-world headlines and summary language for notifications."},
    ],
    "edges": [
        {"from": "Event_Normalizer", "to": "Universe_Bridge", "type": "sequential"},
        {"from": "Universe_Bridge", "to": "Entropy_Engine", "type": "parallel"},
        {"from": "Universe_Bridge", "to": "Style_Analyzer", "type": "parallel"},
        {"from": "Entropy_Engine", "to": "Attractor_Engine", "type": "fan_in"},
        {"from": "Style_Analyzer", "to": "Attractor_Engine", "type": "fan_in"},
        {"from": "Attractor_Engine", "to": "Dramatic_Arc", "type": "sequential"},
        {"from": "Dramatic_Arc", "to": "Phase_Engine", "type": "sequential"},
        {"from": "Phase_Engine", "to": "Singularity_Engine", "type": "sequential"},
        {"from": "Singularity_Engine", "to": "Chief_Editor", "type": "sequential"},
        {"from": "Chief_Editor", "to": "The_Historian", "type": "parallel"},
        {"from": "Chief_Editor", "to": "The_Mythologist", "type": "parallel"},
        {"from": "The_Historian", "to": "The_Psychologist", "type": "fan_in"},
        {"from": "The_Mythologist", "to": "The_Psychologist", "type": "fan_in"},
        {"from": "The_Psychologist", "to": "The_Director", "type": "sequential"},
        {"from": "The_Director", "to": "The_Wordsmith", "type": "sequential"},
        {"from": "The_Wordsmith", "to": "The_Critic", "type": "sequential"},
        {"from": "The_Critic", "to": "VFX_Director", "type": "conditional", "condition": "is_passed or max_revisions"},
        {"from": "The_Critic", "to": "The_Wordsmith", "type": "conditional", "condition": "needs_revision"},
        {"from": "VFX_Director", "to": "The_Archivist", "type": "sequential"},
        {"from": "The_Archivist", "to": "News_Anchor", "type": "sequential"},
    ],
}
